myscrumy/django-ucheokeke16scrumy/ucheokeke16scrumy/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
]

myscrumy/myscrumy/urls.py
from django.contrib import admin
from django.urls import path, include
from ucheokeke16scrumy import views


urlpatterns = [
    path('', include(('ucheokeke16scrumy.urls', 'ucheokeke16scrumy'), namespace='ucheokeke16scrumy')),
    path('admin/', admin.site.urls),
    path('ucheokeke16scrumy/', include('ucheokeke16scrumy.urls', namespace='ucheokeke16scrumy')),
    path('websocket/', include('websocket.urls', namespace='websocket')),
]

myscrumy/ucheokeke16scrumy/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.views import LogoutView

app_name= 'ucheokeke16scrumy'

urlpatterns = [
    path('', views.index, name='index'),
    path('movegoal/<int:goal_id>/', views.move_goal, name='move_goal'),
    path('addgoal/', views.add_goal, name='add_goal'),
    path('home/', views.home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path("logout/", LogoutView.as_view(), name="logout"),
]

myscrumy/django-ucheokeke16scrumy/ucheokeke16scrumy/models.py
from django.db import models

# Create your models here.

myscrumy/ucheokeke16scrumy/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import random
def random_int_gen():
    used_numbers = []
    for i in range(1000, 9999):
        random_int = random.randint(1000, 9999)
        if random_int not in used_numbers:
            used_numbers.append(random_int)
            return random_int
        else:
            continue


class GoalStatus(models.Model):
    CHOICES = [('Weekly Goal', 'Weekly Goal'), ('Daily Goal', 'Daily Goal'), ('Verify Goal', 'Verify Goal'), ('Done Goal', 'Done Goal')]
    status_name = models.CharField(max_length=100, choices=CHOICES)

    def __str__(self):
        return self.status_name


class ScrumyGoals(models.Model):
    objects = models.Manager()
    goal_id = models.IntegerField(default=random_int_gen)
    goal_name = models.CharField(max_length=100)
    created_by = models.CharField(max_length=100, blank=True)
    moved_by = models.CharField(max_length=100, blank=True)
    owner = models.CharField(max_length=100, blank=True)
    def weeklygoal():
        return GoalStatus.objects.get(id=1)
    goal_status = models.ForeignKey(GoalStatus, on_delete=models.PROTECT, default=weeklygoal)
    user = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name='scrumy_goals_user_set')

    def __str__(self):
        return self.goal_name


class ScrumyHistory(models.Model):
    moved_by = models.CharField(max_length=100)
    created_by = models.CharField(max_length=100)
    moved_from = models.CharField(max_length=100)
    moved_to = models.CharField(max_length=100)
    time_of_action = models.DateTimeField(default=timezone.now)
    goal = models.ForeignKey(ScrumyGoals, on_delete=models.PROTECT)

    def __str__(self):
        return self.created_by

# myuser = User.objects.get(username='louis')
# weeklygoal = GoalStatus.objects.get(status_name='Weekly Goal')
# ScrumyGoals.objects.create(goal_name='Learn Django', goal_id=1, created_by='Louis',
#  moved_by='Louis', owner='Louis', goal_status=weeklygoal, user=myuser)

#  creator = ScrumyGoals.objects.get(created_by='Louis')
#  creator.created_by = 'Oma'
#  creator.save()

#  dailygoal = GoalStatus.objects.get(status_name="Daily Goal")
#  weeklygoal = GoalStatus.objects.get(status_name="Weekly Goal")
#  donegoal = GoalStatus.objects.get(status_name="Done Goal")
#  goalstatus = ScrumyGoals.objects.get(goal_status=weeklygoal)
#  goalstatus.goal_status=dailygoal
#  goalstatus.save()
#  seconduser = User.objects.get(username='Wealth')
# ScrumyGoals.objects.create(goal_name='Master Software Development', goal_id=4, created_by='Wealth', moved_by='Wealth', owner='Wealth', goal_status=donegoal, user=seconduser)

myscrumy/ucheokeke16scrumy/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm, Select, TextInput
from .models import ScrumyGoals, GoalStatus


class SignUpForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password'] 

class CreateGoalForm(ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name', 'user']
        widgets = {
            'goal_name' : TextInput(attrs={'class': 'form-control'}),
            'user' : Select(attrs={'class': 'form-control'}),
        }




        

class MoveGoalForm(ModelForm):
    class Meta:
        model = GoalStatus
        fields = ['status_name']
        widget = {
            'status_name': Select(attrs={'class': 'form-control'}),
        }

myscrumy/django-ucheokeke16scrumy/ucheokeke16scrumy/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return HttpResponse("Welcome to Django") 
def get_grading_parameters(request):
    return HttpResponse("Welcome to Django") 

myscrumy/ucheokeke16scrumy/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from . models import ScrumyGoals, GoalStatus, random_int_gen
from django.contrib.auth.models import User, Group
from . forms import SignUpForm, CreateGoalForm, MoveGoalForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

def index(request):
    """ default view of ucheokeke16scrumy """
    form = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse('Your account has been created successfully')
    else:
        form = SignUpForm()
    my_group = Group.objects.get(name = 'Developer')
    all_users = User.objects.all()
    for i in all_users:
        my_group.user_set.add(i)
    context = {'form': form}
    return render(request, 'ucheokeke16scrumy/index.html', context)

@login_required
def move_goal(request, goal_id):
    template = 'ucheokeke16scrumy/movegoal.html'
    groups = Group.objects.all()
    dev = Group.objects.get(name = 'Developer').user_set.all()
    qa = Group.objects.get(name = 'Quality Assurance').user_set.all()
    admin = Group.objects.get(name = 'Admin').user_set.all()
    owner = Group.objects.get(name = 'Owner').user_set.all()
    top3 = [qa,admin,owner]
    message = messages.get_messages(request)

    weekly_goal = GoalStatus.objects.get(status_name="Weekly Goal")
    daily_goal = GoalStatus.objects.get(status_name="Daily Goal")
    verify_goal = GoalStatus.objects.get(status_name="Verify Goal")
    done_goal = GoalStatus.objects.get(status_name="Done Goal")

    obj = get_object_or_404(ScrumyGoals, goal_id=goal_id)
    form = MoveGoalForm(request.POST or None, instance=obj)
    if form.is_valid():
        current_user = request.user
        selected_value = request.POST.get('status_name')
        if current_user in admin or current_user in owner:
            obj.goal_status = GoalStatus.objects.get(status_name = request.POST.get('status_name'))
            obj.save()
            messages.success(request, "You successfully moved the goal")
            return redirect('/home/')
        elif current_user in qa:
            if current_user == obj.user:
                if obj.goal_status == done_goal:
                    if selected_value == 'Weekly Goal':
                        messages.error(request, "You cannot move back to Weekly Column")
                        return redirect('/home/')
                else:
                    obj.goal_status = GoalStatus.objects.get(status_name = request.POST.get('status_name'))
                    obj.save()
                    messages.success(request, "You successfully moved the goal")
                    return redirect('/home/')
            else:
                print("not my goal")
                if obj.goal_status == verify_goal:
                    if selected_value == 'Done Goal':
                        obj.goal_status = GoalStatus.objects.get(status_name = request.POST.get('status_name'))
                        obj.save()
                        messages.success(request, "You successfully moved the goal")
                        return redirect('/home/')
                else:
                    messages.error(request, "You can only move other users' verify goal to done goal")
                    return redirect('/home/')        
        elif current_user in dev:
            if obj.user == current_user:
                if selected_value == 'Done Goal':
                    messages.error(request, "You cannot move goals to Done Goal Column")
                    return redirect('/home/')
                else:
                    obj.goal_status = GoalStatus.objects.get(status_name = request.POST.get('status_name'))
                    obj.save()
                    messages.success(request, "You successfully moved the goal")
                    return redirect('/home/')
            else:
                print('You can only move your goals')
                messages.error(request, "You cannot move other users' goals!")
                return redirect('/home/')
        else:
            print('Kilode ni?')
                      
    context = {'dev':dev, 'qa':qa, 'admin':admin, 'owner': owner,'form':form, 'obj':obj, 'message':message}
    return render(request, template , context)
    

@login_required       
def add_goal(request):
    admin = Group.objects.get(name = 'Admin').user_set.all()
    weekly_goal = GoalStatus.objects.get(status_name="Weekly Goal")

    add_goal_form = CreateGoalForm()
    if request.method == 'POST':
        add_goal_form = CreateGoalForm(request.POST)
        if add_goal_form.is_valid():
            saveform = add_goal_form.save(commit=False)
            if saveform.user != request.user and request.user not in admin and saveform.goal_status != weekly_goal:
                return HttpResponse('You can only create weekly goals for yourself!')
            else:
                saveform.created_by = request.user
                saveform.save()
                print(saveform.goal_id)
                return HttpResponse("Goal Added Successfully!")
    else:
        add_goal_form = CreateGoalForm()
    context = {'add_goal_form': add_goal_form}
    return render(request, 'ucheokeke16scrumy/addgoal.html', context)

@login_required  
def home(request):
    users = User.objects.all()
    weekly_goal = GoalStatus.objects.get(status_name="Weekly Goal")
    daily_goal = GoalStatus.objects.get(status_name="Daily Goal")
    verify_goal = GoalStatus.objects.get(status_name="Verify Goal")
    done_goal = GoalStatus.objects.get(status_name="Done Goal")
    current_user = request.user
    storage = messages.get_messages(request)
    user_group = []
    for g in request.user.groups.all():
        user_group.append(g.name)

    context = {
        'users': users,
        'weekly_goal': weekly_goal,
        'daily_goal': daily_goal,
        'verify_goal': verify_goal,
        'done_goal': done_goal,
        'current_user': current_user,
        'message': storage, 
        'user_group': user_group
    }
    return render(request, 'ucheokeke16scrumy/home.html', context)

myscrumy/ucheokeke16scrumy/templates/ucheokeke16scrumy/addgoal.html
{% extends "base.html" %}

{% block content %}
<h1 style="text-align: center;">Add Goal</h1><br>
<form action="" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="goal_name" class="col-xs-2">Goal name: </label> 
        <div class="col-xs-6">
            {{add_goal_form.goal_name}}
        </div>      
        <br><br>   
    </div>
      <div class="form-group">
        <label for="user" class="col-xs-2">User:</label>
        <div class="col-xs-6">
            {{add_goal_form.user}}
        </div>
        
      </div>

      <div class="form-group">        
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-success">Add Goal</button>
        </div>
      </div>
</form>

{% endblock %}

myscrumy/ucheokeke16scrumy/templates/ucheokeke16scrumy/exception.html
<p style="background-color: red; color: #fff;">{{ error }}</p>

myscrumy/ucheokeke16scrumy/templates/ucheokeke16scrumy/home.html
{% extends "base.html" %}
{% block content %}

<div class="main">
  <div class="user-profile">
    <!-- <img src="https://img.icons8.com/android/24/000000/user.png"/> -->
    <h2>
      <span class="glyphicon glyphicon-user"></span>
      Hey, <span style="color: green;">{{current_user}}</span>!</h2>
    <h4>You are logged in as {{user_group}}</h4>
  </div>

  <div class="messages">
    {% if messages %}
    {% for message in messages %}
      {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-danger" role="alert">
          {{message}}
        </div>
      {% endif %}
      {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
      <div class="alert alert-success" role="alert">
        {{message}}
      </div>
    {% endif %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
    <div class="alert alert-info" role="alert">
      {{message}}
    </div>
  {% endif %}
  {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
  <div class="alert alert-warning" role="alert">
    {{message}}
  </div>
{% endif %}
    {% endfor %}
    {% endif %}
  </div>


<table border="1">
  <!-- <caption style="caption-side:top;"><h1>My Scrumy </h1></caption> -->
    <tr>
      <th>User</th>
      <th>Weekly Goals</th>
      <th>Daily Goals</th>
      <th>Verify Goals</th>
      <th>Done Goals</th>
    </tr>
  {% for user in users %}
    <tr>
      <td>{{ user }}</td>    
      <td>
        {% for i in user.scrumy_goals_user_set.all %}
          {% if i.goal_status == weekly_goal %}
          <div>{{i.goal_name}} {{ i.goal_id }}</div>
          <a href="{% url 'ucheokeke16scrumy:move_goal' i.goal_id %}">move goal</a>
          {% endif %}
        {% endfor %}
      </td>

      <td>
        {% for i in user.scrumy_goals_user_set.all %}
          {% if i.goal_status == daily_goal %}
          <div>{{i.goal_name}} {{ i.goal_id }}</div>
          <a href="{% url 'ucheokeke16scrumy:move_goal' i.goal_id %}">move goal</a>
          {% endif %}
        {% endfor %}
      </td>

      <td>
        {% for i in user.scrumy_goals_user_set.all %}
          {% if i.goal_status == verify_goal %}
          <div>{{i.goal_name}} {{ i.goal_id }}</div>
          <a href="{% url 'ucheokeke16scrumy:move_goal' i.goal_id  %}">move goal</a>
          {% endif %}
        {% endfor %}
      </td>

      <td>
        {% for i in user.scrumy_goals_user_set.all %}
          {% if i.goal_status == done_goal %}
           <div>{{i.goal_name}} {{ i.goal_id }}</div>
           <a href="{% url 'ucheokeke16scrumy:move_goal' i.goal_id %}">move goal</a>
          {% endif %}
        {% endfor %}
      </td>
    </tr>
  {%endfor%}
</table>
<br>
<h3 style="width: 90%;margin: auto;"><a href="{% url 'ucheokeke16scrumy:add_goal' %}">Add Goal</a></h3>
<br><br>
</div> <!-- End of main -->
{% endblock %}

myscrumy/ucheokeke16scrumy/templates/ucheokeke16scrumy/index.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h2>Signup Form</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
      <div class="form-group">
        <label class="control-label col-sm-2" for="first_name">First name:</label>
        <div class="col-sm-10">
            {{form.first_name}}
        </div>
      </div>

      <div class="form-group">
        <label class="control-label col-sm-2" for="pwd">Last name:</label>
        <div class="col-sm-10">          
             {{form.last_name}}
        </div>
      </div>

      <div class="form-group">
        <label class="control-label col-sm-2" for="pwd">Email:</label>
        <div class="col-sm-10">          
             {{form.email}}
        </div>
      </div>

      <div class="form-group">
        <label class="control-label col-sm-2" for="pwd">Username:</label>
        <div class="col-sm-10">          
             {{form.username}}
        </div>
      </div>
       
      <div class="form-group">
        <label class="control-label col-sm-2" for="pwd">Password:</label>
        <div class="col-sm-10">          
            {{form.password}} <br>
            <small class="form-text text-muted">(Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only)</small>
        </div>    
      </div>

      <div class="form-group">        
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-success">Sign Up</button>
          <span>Already have an account? <a href="{% url 'ucheokeke16scrumy:login' %}"> Login</a></span>
        </div>
      </div>
    </form>
  </div>


{% endblock %}

myscrumy/ucheokeke16scrumy/templates/ucheokeke16scrumy/movegoal.html
{% extends "base.html" %}
{% block content %}

<div class="messages">
  {% if messages %}
  {% for message in messages %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
      <div class="alert alert-danger" role="alert">
        {{message}}
      </div>
    {% endif %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
    <div class="alert alert-success" role="alert">
      {{message}}
    </div>
  {% endif %}
  {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
  <div class="alert alert-info" role="alert">
    {{message}}
  </div>
{% endif %}
{% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
<div class="alert alert-warning" role="alert">
  {{message}}
</div>
{% endif %}
  {% endfor %}
  {% endif %}
</div>

<h3>Move Goal from {{ obj.goal_status }} To: </h3><hr>
<form action="" method="post" >
    {% csrf_token %}
    <div class="form-group">
      <label for="user">Status name: </label>
        {{form.status_name}}
    </div>  
    <button type="submit" class="btn btn-success">Move Goal</button>

</form>

<p><a href="{% url 'ucheokeke16scrumy:home' %}">Go Back Home</a></p>

{% endblock %}